// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgPjoVwTYhEldF2rWQpCjRd8FjAnIaF_8',
    appId: '1:983751025225:web:15f889d1523d6039825598',
    messagingSenderId: '983751025225',
    projectId: 'our-shops-4a456',
    authDomain: 'our-shops-4a456.firebaseapp.com',
    storageBucket: 'our-shops-4a456.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqyq0rLsa-hIB8k4_VO4L4-sQv7KkyBMM',
    appId: '1:983751025225:android:8b0035e5d56339d4825598',
    messagingSenderId: '983751025225',
    projectId: 'our-shops-4a456',
    storageBucket: 'our-shops-4a456.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmvt5E-JbXbF-00RiLXEaVv7pIrxg9Lm0',
    appId: '1:983751025225:ios:b7bc078d682a2306825598',
    messagingSenderId: '983751025225',
    projectId: 'our-shops-4a456',
    storageBucket: 'our-shops-4a456.appspot.com',
    iosClientId: '983751025225-h17gn4kk7dndcb5hlmb3736lssj79r9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourShops',
  );
}
